### ISSUE TITLE
Unwanted loading of full items in catalog view

### ISSUE THREAD

**Issue by rebastion** [bekarice/woocommerce-extra-product-sorting-options#5]
for some reason, the plugin creates an URL like http://mydomain.com/catalog/page/2/?orderby=popularity

**Comment by bekarice** [comment]
Hey @rebastion, this is expected behavior, as this is how WooCommerce passes in the sorting order to the page. If you deactivate the plugin, you'll find that WooCommerce core does this when you change the sorting order with the dropdown on your shop page, and it's not added by this plugin.
